### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by ghost** [HarrieO/OnlineLearningToRank#1]
Can you tell us how to use the packing code ?
for example, providing a example or tutorial,thank you.

**Comment by HarrieO** [comment]
Hi Kevin,

I will provide some instructions on how to setup the environment and rerun the experiments from the paper.
Expect them within the next two weeks.

**Comment by ghost** [comment]
OK, thanks, I am looking forward to the instructions.

**Comment by RBeaudet** [comment]
Hi, 
I've read your paper with interest and would be glad if you could provide some instructions on how to use the code (i.e. how should the data be, how to you use it when data come on the fly, etc.). Thank you !

**Comment by DominickZhang** [comment]
Hi,
I am also interested in the instructions. Thank you!

**Comment by HarrieO** [comment]
Sorry for the delay!
I've updated the README with the command that reproduces the paper results, you will have to download the datasets and link them in (utils/datasetcollections.py) by updating the paths in that file.
